# Generated by Django 5.0.2 on 2024-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['-time_create'], name='notes_notes_time_cr_8d163d_idx'),
        ),
    ]
