# Generated by Django 5.0.2 on 2024-05-24 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='notes',
            name='foot_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='notes.footnote', verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='notes.tagpost', verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['-time_create'], name='notes_notes_time_cr_8d163d_idx'),
        ),
    ]
