# Generated by Django 5.0.2 on 2024-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Личное'), (1, 'Опубликовано')], default=0),
        ),
    ]
