# Generated by Django 5.0.2 on 2024-04-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_category_notes_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.category'),
        ),
    ]
