# Generated by Django 5.0.2 on 2024-04-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_tagpost_notes_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='foot_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='notes.footnote'),
        ),
    ]
