# Generated by Django 5.0.2 on 2024-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_uploadfiles_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pictures/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
